export const workPosition = [
  "HR Representative",
  "CEO",
  "CTO",
  "COO",
  "CFO",
  "CMO",
];

export const locationOptions = [
  "Greater Accra Region",
  "Ashanti Region",
  "Central Region",
  "Eastern Region",
  "Brong Ahafo Region",
  "Northern Region",
  "Upper East Region",
  "Upper West Region",
  "Western North Region",
  "North East Region",
  "Oti Region",
  "Bono East Region",
  "Ahafo Region",
  "Savannah Region",
  "Volta Region",
  "Western Region",
  "Worldwide",
];

export const jobType = ["Internship", "Contract", "Entry level", "NSS"];

export const jobStyle = ["On-site", "Remote", "Hybrid"];

export const skillsList = [
  "HTML",
  "CSS",
  "CSS",
  "Bootstrap",
  "Vue",
  "React.js",
  "Javascript",
  "PHP",
  "Web Development",
  "Excel",
  "Word",
  "MS Office",
  "Algorithms",
  "Analytical Skills",
  "Big Data",
  "Calculating",
  "Compiling Statistics",
  "Data Analytics",
  "Data Mining",
  "Database Design",
  "Database Management",
  "Documentation",
  "Modeling",
  "Modification",
  "Needs Analysis",
  "Quantitative Research",
  "Quantitative Reports",
  "Statistical Analysis",
  "Applications",
  "Certifications",
  "Coding",
  "Computing",
  "Configuration",
  "Customer Support",
  "Debugging",
  "Design",
  "Development",
  "Hardware",
  "Implementation",
  "Information Technology",
  "Infrastructure",
  "Languages",
  "Maintenance",
  "Network Architecture",
  "Network Security",
  "Networking",
  "New Technologies",
  "Operating Systems",
  "Programming",
  "Restoration",
  "Security",
  "Servers",
  "Software",
  "Solution Delivery",
  "Storage",
  "Structures",
  "Systems Analysis",
  "Technical Support",
  "Technology",
  "Testing",
  "Tools",
  "Training",
  "Troubleshooting",
  "Usability",
  "Benchmarking",
  "Budget Planning",
  "Engineering",
  "Fabrication",
  "Following Specifications",
  "Operations",
  "Performance Review",
  "Project Planning",
  "Quality Assurance",
  "Quality Control",
  "Scheduling",
  "Task Delegation",
  "Task Management",
  "Blogging",
  "Digital Photography",
  "Digital Media",
  "Facebook",
  "Instagram",
  "Networking",
  "Pinterest",
  "SEO",
  "Social Media Platforms",
  "Twitter",
  "Web Analytics",
  "Client Relations",
  "Email",
  "Requirements Gathering",
  "Research",
  "Subject Matter Experts (SMEs)",
  "Technical Documentation",
  "UI Design",
  "UX Design",
  "UI/UX Design",
  "Product Design",
  "Color Grading",
  "Cinematography",
  "Video Editing",
  "Print",
  "Problem Solving",
  "Adaptability",
  "Openness",
  "People skills",
  "Leadership",
  "Extroversion",
  "Responsibility",
  "Teamwork",
  "Effective communication",
  "Data analysis",
  "Web analytics",
  "SEO/SEM",
  "HTML & CSS",
  "Wordpress",
  "Email marketing",
  "Web scraping",
  "CRO and A/B Testing",
  "Data visualization & pattern-finding through critical thinking",
  "Search Engine and Keyword Optimization",
  "Project/campaign management",
  "Social media and mobile marketing ",
  "Paid social media advertisements",
  "BB Marketing",
  "The  P-s of Marketing",
  "Consumer Behavior Drivers",
  "Brand management",
  "Creativity",
  "Copywriting",
  "Storytelling",
  "Sales",
  "CMS Tools",
  "Six Sigma techniques",
  "The McKinsey s Framework",
  "Porters Five Forces",
  "PESTEL ",
  "Emotional Intelligence",
  "Dealing with work-related stress",
  "Motivation",
  "Task delegation",
  "Technological savviness",
  "People management",
  "Business Development",
  "Strategic Management",
  "Negotiation",
  "Planning",
  "Proposal writing",
  "Problem-solving",
  "Innovation",
  "Charisma",
  "Customer Relationship Management (CRM)",
  "Cold-calling",
  "Negotiation",
  "Public speaking",
  "Closing",
  "Lead generation",
  "Buyer-Responsive selling",
  "Buyer engagement",
  "Product knowledge",
  "Persuasion",
  "Effective communication and sociability",
  "Empathy",
  "Social media/digital communication",
  "Teamwork",
  "Time management",
  "Adobe Creative Suite: Illustrator, InDesign, Photoshop",
  "Dreamweaver",
  "Infographics",
  "HTML & CSS",
  "Photo editing ",
  "Typography: spacing, line height, layout, choosing fonts",
  "Storyboarding",
  "Targeting and marketing through visual communications",
  "Logo Design",
  "Digital printing",
  "Integration of visual communication in social media platforms",
  "Creativity",
  "Attention to detail & aesthetics",
  "Interactive media design",
  "Color sense & theory",
  "Ad design",
  "Active listening",
  "Microsoft Office Pack: Word, Excel, Access, Publisher, Outlook, Powerpoint",
  "Filing and paper management",
  "Data entry",
  "Bookkeeping through Excel or TurboTax",
  "Research and data analysis",
  "Basic knowledge of user interface communication",
  "Technical writing",
  "Cloud networking and file sharing ",
  "Microsoft Excel (Advanced)",
  "Enterprise Resource Planning",
  "Big Data Analysis & SQL",
  "Know Your Customers (KYC)",
  "Cognos Analytics (IBM)",
  "Visual Basic",
  "Accounting Software",
  "Revenue recognition",
  "Anti Money Laundering",
  "Clear communication",
  "General business knowledge",
  "Numerical competence",
  "Accuracy",
  "Attention to detail",
  "Updated curriculum knowledge",
  "Research & Data analysis",
  "Communication",
  "Educational platforms (software like Elearn)",
  "Stress management",
  "Technological & digital literacy",
  "Patience",
  "Critical thinking",
  "Enthusiasm",
  "Motivation",
  "CSS preprocessors",
  "Wordpress",
  "Webflow",
  "Graphic User Interfaces (GUI)",
  "Git/Version control (Github, gitlab)",
  "Search Engine Optimization (SEO)",
  "Application Programming Interface (API)",
  "Adobe Photoshop, InDesign",
  "Content Management Systems (CMS)",
  "Testing/Debugging",
  "Responsive design principles",
  "STATA, SPSS, SAS ",
  "Data Mapping",
  "Entity Relationship Diagrams",
  "Wireframes",
  "Big Data tools",
  "Microsoft Visio",
  "Agile Business Analysis",
  "Machine learning",
  "System Context Diagrams",
  "Business Process Modeling",
  "Technical and non-technical communication",
  "Mathematics",
  "CPR",
  "Patient care and assistance",
  "Paperwork/record-keeping abilities",
  "Compassion",
  "Advanced Cardiac Life Support (ACLS)",
  "Telemetry",
  "Attention to detail",
  "Physical endurance ",
  "Acute care",
  "Infection control",
  "Surgery preparation",
];

export const jobCategory = [
  "Software Development",
  "Data Science",
  "Design",
  "Marketing",
  "Sales",
  "Customer Service",
  "Finance",
  "Human Resources",
];
