export const workPosition = [
  "CEO",
  "CFO",
  "CHRO",
  "CMO",
  "COO",
  "CTO",
  "HR Representative",
];

export const locationOptions = [
  "Ahafo Region",
  "Ashanti Region",
  "Bono East Region",
  "Brong Ahafo Region",
  "Central Region",
  "Eastern Region",
  "Greater Accra Region",
  "North East Region",
  "Northern Region",
  "Oti Region",
  "Savannah Region",
  "Upper East Region",
  "Upper West Region",
  "Volta Region",
  "Western North Region",
  "Western Region",
  "Worldwide",
];

export const salaryRanges = ["0 - 1k", "1k - 3k", "3k - 5k", "Confidential"];

export const jobTypes = ["Contract", "Entry level", "Internship", "NSS"];

export const jobStyles = ["Hybrid", "On-site", "Remote"];

export const skillsList = [
  "3D Modeling",
  "Adobe Creative Suite: Illustrator, InDesign, Photoshop",
  "Adobe Photoshop, InDesign",
  "Advanced Cardiac Life Support (ACLS)",
  "Agile Business Analysis",
  "Algorithms",
  "Analytical Skills",
  "Applications",
  "Attention to detail",
  "Attention to detail & aesthetics",
  "Big Data",
  "Big Data Analysis & SQL",
  "Big Data tools",
  "Blogging",
  "Bootstrap",
  "Brand management",
  "Budget Planning",
  "Business Development",
  "Business Process Modeling",
  "Buyer engagement",
  "Buyer-Responsive selling",
  "CRO and A/B Testing",
  "CSS",
  "CSS preprocessors",
  "Calculating",
  "Charisma",
  "Clear communication",
  "Client Relations",
  "Cloud networking and file sharing ",
  "Closing",
  "Coding",
  "Cold-calling",
  "Color Grading",
  "Color sense & theory",
  "Compassion",
  "Compiling Statistics",
  "Configuration",
  "Consumer Behavior Drivers",
  "Content Management Systems (CMS)",
  "Content Management Systems (CMS)",
  "Creativity",
  "Critical thinking",
  "Customer Relationship Management (CRM)",
  "Customer Support",
  "Data Analytics",
  "Data Mapping",
  "Data Mining",
  "Data analysis",
  "Data entry",
  "Data visualization & pattern-finding through critical thinking",
  "Database Design",
  "Database Management",
  "Debugging",
  "Dealing with work-related stress",
  "Design",
  "Development",
  "Digital Media",
  "Digital Photography",
  "Digital printing",
  "Documentation",
  "Dreamweaver",
  "Effective communication",
  "Effective communication and sociability",
  "Educational platforms (software like Elearn)",
  "Email",
  "Email marketing",
  "Emotional Intelligence",
  "Enterprise Resource Planning",
  "Entity Relationship Diagrams",
  "Excel",
  "Extroversion",
  "Fabrication",
  "Facebook",
  "Filing and paper management",
  "Following Specifications",
  "Git/Version control (Github, gitlab)",
  "Graphic User Interfaces (GUI)",
  "Hardware",
  "Healthcare",
  "HTML",
  "HTML & CSS",
  "Human Resources",
  "Implementation",
  "Infection control",
  "Information Technology",
  "Innovation",
  "Interactive media design",
  "Integration of visual communication in social media platforms",
  "Languages",
  "Lead generation",
  "Leadership",
  "Logo Design",
  "Machine learning",
  "Maintenance",
  "Marketing",
  "Mathematics",
  "Microsoft Excel (Advanced)",
  "Microsoft Office Pack: Word, Excel, Access, Publisher, Outlook, Powerpoint",
  "Microsoft Visio",
  "Modeling",
  "Modification",
  "Motivation",
  "MS Office",
  "Negotiation",
  "Networking",
  "New Technologies",
  "Numerical competence",
  "Oti Region",
  "Operating Systems",
  "Openness",
  "Paperwork/record-keeping abilities",
  "Patience",
  "Patient care and assistance",
  "Performance Review",
  "Persuasion",
  "Photo editing ",
  "Pinterest",
  "Planning",
  "Print",
  "Problem Solving",
  "Problem-solving",
  "Product Design",
  "Product knowledge",
  "Programming",
  "Project Planning",
  "Project/campaign management",
  "Proposal writing",
  "Public speaking",
  "Quantitative Reports",
  "Quantitative Research",
  "Quality Assurance",
  "Quality Control",
  "React.js",
  "Real Estate",
  "Research",
  "Research & Data analysis",
  "Requirements Gathering",
  "Restoration",
  "Revenue recognition",
  "Sales",
  "Scheduling",
  "Search Engine Optimization (SEO)",
  "Search Engine and Keyword Optimization",
  "Security",
  "SEO",
  "SEO/SEM",
  "Servers",
  "Six Sigma techniques",
  "Social Media Platforms",
  "Social media and mobile marketing ",
  "Social media/digital communication",
  "Software",
  "Solution Delivery",
  "Surgery preparation",
  "Systems Analysis",
  "Task Delegation",
  "Task Management",
  "Task delegation",
  "Teamwork",
  "Technical Documentation",
  "Technical Support",
  "Technical and non-technical communication",
  "Technical writing",
  "Technological & digital literacy",
  "Technological savviness",
  "Technology",
  "Telemetry",
  "Testing",
  "Testing/Debugging",
  "The McKinsey s Framework",
  "The P-s of Marketing",
  "Time management",
  "Tools",
  "Training",
  "Troubleshooting",
  "Twitter",
  "Typography: spacing, line height, layout, choosing fonts",
  "UI Design",
  "UI/UX Design",
  "Updated curriculum knowledge",
  "Usability",
  "UX Design",
  "Video Editing",
  "Visual Basic",
  "Visual communication",
  "Visual storytelling",
  "Web Development",
  "Web analytics",
  "Web scraping",
  "Webflow",
  "Wireframes",
  "Word",
  "Wordpress",
  "Worldwide",
];

export const jobCategory = [
  "Agriculture",
  "Consulting",
  "Construction",
  "Content Creation",
  "Customer Service",
  "Data Science",
  "Design",
  "Education",
  "Energy",
  "Engineering",
  "Entertainment",
  "Finance",
  "Government",
  "Healthcare",
  "Hospitality",
  "Human Resources",
  "Legal",
  "Logistics",
  "Manufacturing",
  "Marketing",
  "Media",
  "Non-Profit",
  "Operations",
  "Pharmaceuticals",
  "Project Management",
  "Real Estate",
  "Retail",
  "Sales",
  "Software Development",
  "Telecommunications",
  "Transportation",
  "Travel",
  "Web Development",
  "Writing",
  "Other",
];
